name: logman
description: A Logger package with UI
version: 0.0.2
homepage: https://github.com/Sorcel-Tech/logman.dart

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  logger: ^2.0.2+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:


