name: logman
description: A simple yet powerful logging package for Flutter apps with an integrated UI and an optional debug page.
version: 0.1.1
homepage: https://github.com/Sorcel-Tech/logman.dart

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  intl: ^0.20.2
  logger: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:


